#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
verifier="$script_dir/verify_shipping_fork_pins.sh"

if [[ ! -x "$verifier" ]]; then
  echo "shipping fork pin verifier regression setup failed: missing executable $verifier" >&2
  exit 1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

seed="$tmpdir/seed"
mkdir -p "$seed"
git -C "$seed" init -q
git -C "$seed" config user.name "Axon shipping pin verifier test"
git -C "$seed" config user.email "shipping-pin-verifier@example.invalid"
printf '%s\n' "approved fork revision" >"$seed/README.md"
git -C "$seed" add README.md
git -C "$seed" commit -q -m "test: publish approved fork revision"
approved_rev="$(git -C "$seed" rev-parse HEAD)"
git -C "$seed" tag approved-lightweight
git -C "$seed" tag -a approved-annotated -m "approved annotated publication"
approved_bare="$tmpdir/approved.git"
git clone -q --bare "$seed" "$approved_bare"
approved_url="file://$approved_bare"

write_fixture() {
  local fixture="$1"
  mkdir -p "$fixture/crates/example"

  cat >"$fixture/Cargo.toml" <<EOF_MANIFEST
[workspace]
members = ["crates/example"]
resolver = "2"

[workspace.dependencies]
approved = { git = "$approved_url", rev = "$approved_rev" }
EOF_MANIFEST

  cat >"$fixture/crates/example/Cargo.toml" <<'EOF_MEMBER'
[package]
name = "shipping-pin-fixture"
version = "0.1.0"
edition = "2021"

[dependencies]
approved = { workspace = true }
EOF_MEMBER

  cat >"$fixture/Cargo.lock" <<EOF_LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "approved"
version = "0.1.0"
source = "git+$approved_url?rev=$approved_rev#$approved_rev"
EOF_LOCK

  cat >"$fixture/policy.toml" <<EOF_POLICY
schema = 1

[[pins]]
repository = "$approved_url"
revision = "$approved_rev"
publication_ref = "refs/heads/main"
EOF_POLICY
}

run_verifier() {
  local fixture="$1"
  bash "$verifier" \
    --repo-root "$fixture" \
    --policy-file "$fixture/policy.toml"
}

expect_failure() {
  local name="$1"
  local expected="$2"
  local fixture="$3"
  local output="$tmpdir/$name.output"
  if run_verifier "$fixture" >"$output" 2>&1; then
    echo "expected $name to fail" >&2
    exit 1
  fi
  if ! rg -F "$expected" "$output" >/dev/null; then
    echo "$name failed without expected diagnostic: $expected" >&2
    cat "$output" >&2
    exit 1
  fi
}

base="$tmpdir/base"
write_fixture "$base"
run_verifier "$base" >/dev/null

non_dependency_metadata="$tmpdir/non-dependency-metadata"
cp -R "$base" "$non_dependency_metadata"
cat >>"$non_dependency_metadata/crates/example/Cargo.toml" <<'EOF_METADATA'

[package.metadata.shipping-pin-fixture]
git = "https://github.com/example/documentation-only"
EOF_METADATA
run_verifier "$non_dependency_metadata" >/dev/null

table_form_dependency="$tmpdir/table-form-dependency"
cp -R "$base" "$table_form_dependency"
python3 - "$table_form_dependency/Cargo.toml" "$approved_url" "$approved_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
url = sys.argv[2]
revision = sys.argv[3]
inline = f'approved = {{ git = "{url}", rev = "{revision}" }}'
table = (
    "[workspace.dependencies.approved]\n"
    f'git = "{url}"\n'
    f'rev = "{revision}"'
)
path.write_text(path.read_text().replace(inline, table))
PY
run_verifier "$table_form_dependency" >/dev/null

unapproved_target_dependency="$tmpdir/unapproved-target-dependency"
cp -R "$base" "$unapproved_target_dependency"
cat >>"$unapproved_target_dependency/crates/example/Cargo.toml" <<'EOF_TARGET_DEPENDENCY'

[target.'cfg(target_arch = "wasm32")'.dependencies]
unapproved_target = { git = "https://github.com/example/unapproved-target", rev = "0000000000000000000000000000000000000000" }
EOF_TARGET_DEPENDENCY
expect_failure \
  "unapproved-target-dependency" \
  "unapproved Git repository" \
  "$unapproved_target_dependency"

unapproved_patch_dependency="$tmpdir/unapproved-patch-dependency"
cp -R "$base" "$unapproved_patch_dependency"
cat >>"$unapproved_patch_dependency/Cargo.toml" <<'EOF_PATCH_DEPENDENCY'

[patch.crates-io]
unapproved_patch = { git = "https://github.com/example/unapproved-patch", rev = "0000000000000000000000000000000000000000" }
EOF_PATCH_DEPENDENCY
expect_failure \
  "unapproved-patch-dependency" \
  "unapproved Git repository" \
  "$unapproved_patch_dependency"

mutable_branch="$tmpdir/mutable-branch"
cp -R "$base" "$mutable_branch"
python3 - "$mutable_branch/Cargo.toml" "$approved_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
revision = sys.argv[2]
path.write_text(path.read_text().replace(f'rev = "{revision}"', 'branch = "main"'))
PY
expect_failure \
  "mutable-branch" \
  "mutable or unpinned fork dependency" \
  "$mutable_branch"

unapproved_repository="$tmpdir/unapproved-repository"
cp -R "$base" "$unapproved_repository"
cat >>"$unapproved_repository/Cargo.toml" <<'EOF_UNAPPROVED'
unapproved = { git = "https://github.com/daxis-io/unapproved", rev = "0000000000000000000000000000000000000000" }
EOF_UNAPPROVED
expect_failure \
  "unapproved-repository" \
  "unapproved Git repository" \
  "$unapproved_repository"

unapproved_external_repository="$tmpdir/unapproved-external-repository"
cp -R "$base" "$unapproved_external_repository"
cat >>"$unapproved_external_repository/Cargo.toml" <<'EOF_UNAPPROVED_EXTERNAL'
unapproved_external = { git = "https://github.com/example/unapproved", rev = "0000000000000000000000000000000000000000" }
EOF_UNAPPROVED_EXTERNAL
expect_failure \
  "unapproved-external-repository" \
  "unapproved Git repository" \
  "$unapproved_external_repository"

unapproved_external_lock="$tmpdir/unapproved-external-lock"
cp -R "$base" "$unapproved_external_lock"
cat >>"$unapproved_external_lock/Cargo.lock" <<'EOF_UNAPPROVED_EXTERNAL_LOCK'

[[package]]
name = "unapproved-external"
version = "0.1.0"
source = "git+https://github.com/example/unapproved?rev=0000000000000000000000000000000000000000#0000000000000000000000000000000000000000"
EOF_UNAPPROVED_EXTERNAL_LOCK
expect_failure \
  "unapproved-external-lock" \
  "unapproved Git repository in Cargo.lock" \
  "$unapproved_external_lock"

canonical_repository_identity="$tmpdir/canonical-repository-identity"
cp -R "$base" "$canonical_repository_identity"
python3 - \
  "$canonical_repository_identity/Cargo.toml" \
  "$canonical_repository_identity/Cargo.lock" \
  "$canonical_repository_identity/policy.toml" \
  "$approved_url" <<'PY'
from pathlib import Path
import sys

manifest_path = Path(sys.argv[1])
lock_path = Path(sys.argv[2])
policy_path = Path(sys.argv[3])
old_url = sys.argv[4]

manifest_path.write_text(
    manifest_path.read_text().replace(
        old_url,
        "git@github.com:DAXIS-IO/APPROVED.git",
    )
)
lock_path.write_text(
    lock_path.read_text().replace(
        old_url,
        "ssh://git@github.com:22/daxis-io/approved.git",
    )
)
policy_path.write_text(
    policy_path.read_text().replace(
        old_url,
        "https://github.com/daxis-io/approved",
    )
)
PY
fake_git_bin="$tmpdir/canonical-git-bin"
mkdir -p "$fake_git_bin"
real_git="$(command -v git)"
cat >"$fake_git_bin/git" <<'EOF_FAKE_GIT'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "ls-remote" ]]; then
  if [[ "${GIT_TERMINAL_PROMPT:-}" != "0" ]]; then
    echo "GIT_TERMINAL_PROMPT must be disabled" >&2
    exit 91
  fi
  printf '%s\t%s\n' "$FAKE_GIT_REVISION" "refs/heads/main"
  exit 0
fi
exec "$REAL_GIT" "$@"
EOF_FAKE_GIT
chmod +x "$fake_git_bin/git"
PATH="$fake_git_bin:$PATH" \
  REAL_GIT="$real_git" \
  FAKE_GIT_REVISION="$approved_rev" \
  run_verifier "$canonical_repository_identity" >/dev/null

canonical_https_userinfo="$tmpdir/canonical-https-userinfo"
cp -R "$canonical_repository_identity" "$canonical_https_userinfo"
python3 - "$canonical_https_userinfo/Cargo.toml" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(
    path.read_text().replace(
        "git@github.com:DAXIS-IO/APPROVED.git",
        "https://fixture-user@github.com:443/DAXIS-IO/APPROVED.git",
    )
)
PY
PATH="$fake_git_bin:$PATH" \
  REAL_GIT="$real_git" \
  FAKE_GIT_REVISION="$approved_rev" \
  run_verifier "$canonical_https_userinfo" >/dev/null

timeout_git_bin="$tmpdir/timeout-git-bin"
mkdir -p "$timeout_git_bin"
cat >"$timeout_git_bin/git" <<'EOF_TIMEOUT_GIT'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "ls-remote" ]]; then
  sleep 2
  exit 0
fi
exec "$REAL_GIT" "$@"
EOF_TIMEOUT_GIT
chmod +x "$timeout_git_bin/git"
timeout_output="$tmpdir/remote-timeout.output"
if PATH="$timeout_git_bin:$PATH" \
  REAL_GIT="$real_git" \
  AXON_SHIPPING_FORK_GIT_TIMEOUT_SECONDS=1 \
  run_verifier "$base" >"$timeout_output" 2>&1; then
  echo "expected remote timeout to fail" >&2
  exit 1
fi
if ! rg -F "timed out" "$timeout_output" >/dev/null; then
  echo "remote timeout failed without timeout diagnostic" >&2
  cat "$timeout_output" >&2
  exit 1
fi

retry_git_bin="$tmpdir/retry-git-bin"
mkdir -p "$retry_git_bin"
cat >"$retry_git_bin/git" <<'EOF_RETRY_GIT'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" == "ls-remote" ]]; then
  attempt=0
  if [[ -f "$GIT_RETRY_COUNTER" ]]; then
    attempt="$(<"$GIT_RETRY_COUNTER")"
  fi
  attempt="$((attempt + 1))"
  printf '%s\n' "$attempt" >"$GIT_RETRY_COUNTER"
  if [[ "$attempt" -eq 1 ]]; then
    echo "transient transport failure" >&2
    exit 75
  fi
fi
exec "$REAL_GIT" "$@"
EOF_RETRY_GIT
chmod +x "$retry_git_bin/git"
retry_counter="$tmpdir/retry-counter"
PATH="$retry_git_bin:$PATH" \
  REAL_GIT="$real_git" \
  GIT_RETRY_COUNTER="$retry_counter" \
  run_verifier "$base" >/dev/null
if [[ "$(<"$retry_counter")" != "2" ]]; then
  echo "expected one bounded retry after a transport failure" >&2
  exit 1
fi

manifest_revision_mismatch="$tmpdir/manifest-revision-mismatch"
cp -R "$base" "$manifest_revision_mismatch"
python3 - "$manifest_revision_mismatch/Cargo.toml" "$approved_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
revision = sys.argv[2]
path.write_text(
    path.read_text().replace(
        f'rev = "{revision}"',
        'rev = "0000000000000000000000000000000000000000"',
    )
)
PY
expect_failure \
  "manifest-revision-mismatch" \
  "manifest revision mismatch" \
  "$manifest_revision_mismatch"

lock_revision_mismatch="$tmpdir/lock-revision-mismatch"
cp -R "$base" "$lock_revision_mismatch"
python3 - "$lock_revision_mismatch/Cargo.lock" "$approved_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
revision = sys.argv[2]
path.write_text(
    path.read_text().replace(
        f"#{revision}",
        "#0000000000000000000000000000000000000000",
    )
)
PY
expect_failure \
  "lock-revision-mismatch" \
  "Cargo.lock source mismatch" \
  "$lock_revision_mismatch"

publication_ref_mismatch="$tmpdir/publication-ref-mismatch"
cp -R "$base" "$publication_ref_mismatch"
python3 - "$publication_ref_mismatch/policy.toml" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(path.read_text().replace("refs/heads/main", "refs/heads/missing"))
PY
expect_failure \
  "publication-ref-mismatch" \
  "published ref mismatch" \
  "$publication_ref_mismatch"

invalid_publication_ref="$tmpdir/invalid-publication-ref"
cp -R "$base" "$invalid_publication_ref"
python3 - "$invalid_publication_ref/policy.toml" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(path.read_text().replace("refs/heads/main", "refs/heads/*"))
PY
expect_failure \
  "invalid-publication-ref" \
  "invalid publication ref" \
  "$invalid_publication_ref"

invalid_refs=(
  "refs/heads/topic..nested"
  "refs/heads/topic@{1}"
  "refs/heads/trailing."
  "refs/heads/reserved.lock"
  "refs/heads/topic^suffix"
  "refs/heads/topic:segment"
)
for index in "${!invalid_refs[@]}"; do
  invalid_ref_fixture="$tmpdir/invalid-publication-ref-$index"
  cp -R "$base" "$invalid_ref_fixture"
  python3 - "$invalid_ref_fixture/policy.toml" "${invalid_refs[$index]}" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(path.read_text().replace("refs/heads/main", sys.argv[2]))
PY
  expect_failure \
    "invalid-publication-ref-$index" \
    "invalid publication ref" \
    "$invalid_ref_fixture"
done

lightweight_tag="$tmpdir/lightweight-tag"
cp -R "$base" "$lightweight_tag"
python3 - "$lightweight_tag/policy.toml" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(path.read_text().replace("refs/heads/main", "refs/tags/approved-lightweight"))
PY
run_verifier "$lightweight_tag" >/dev/null

annotated_tag="$tmpdir/annotated-tag"
cp -R "$base" "$annotated_tag"
python3 - "$annotated_tag/policy.toml" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
path.write_text(path.read_text().replace("refs/heads/main", "refs/tags/approved-annotated"))
PY
run_verifier "$annotated_tag" >/dev/null

echo "shipping fork pin verifier regression coverage passed"
