#!/usr/bin/env bash

set -euo pipefail

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

repo_root="$tmpdir/repo"
packet="$repo_root/docs/release-gates/daxis-external-proof-packet.json"
traceability="$repo_root/docs/release-gates/daxis-strategy-traceability.json"
release_bundle="$repo_root/docs/release-gates/daxis-release-bundle-manifest.json"
rollout_register="$repo_root/docs/release-gates/daxis-production-rollout-decisions.json"

mkdir -p "$repo_root/docs/program" "$repo_root/docs/release-gates" "$repo_root/tests/conformance"

for doc in \
	docs/adr/ADR-0008-daxis-browser-read-compute-contract.md \
	docs/integrations/daxis/daxis-first-class-integration-strategy.md \
	docs/integrations/daxis/daxis-operational-maturity.md \
	docs/integrations/daxis/daxis-external-proof-handoff.md \
	docs/release-gates/daxis-external-proof-attachment-template.md \
	docs/release-gates/daxis-dirty-worktree-review-template.json \
	docs/release-gates/daxis-strategy-traceability.json \
	docs/release-gates/daxis-release-bundle-manifest.json \
	docs/release-gates/daxis-production-rollout-decisions.json \
	docs/release-gates/daxis-operational-readiness.json \
	docs/release-gates/browser-wasm-delta-gcs-external-blockers.md \
	tests/conformance/verify_daxis_external_proof_attachment.sh \
	tests/conformance/verify_daxis_stable_default_promotion_packet.sh \
	tests/conformance/verify_daxis_stable_default_promotion_packet_test.sh; do
	mkdir -p "$repo_root/$(dirname "$doc")"
	printf '# test fixture\n' >"$repo_root/$doc"
done

write_proof_attachment_template() {
	cat >"$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'EOF'
# Daxis External Proof Attachment Template

Do not attach browser-visible secrets, signed URLs, raw credentials, service-account material, private customer identifiers, or unredacted tenant data.

## Proof Attachment Metadata

- item_id:
- milestone:
- owner:
- captured_at:
- environment:
- environment_class:
- release_channel:
- axon_release_commit_sha:
- axon_release_ref:
- rollout_segment:
- artifact_uri:
- verification_command_or_url:
- exit_status_or_review_status:
- rollback_evidence_uri:
- daxis_commit_sha:
- daxis_ref:
- daxis_origin_remote_url:
- daxis_worktree_status:
- daxis_worktree_review:
- daxis_external_state_schema_version:
- daxis_external_state_json_uri:
- daxis_external_state_json_sha256:
- daxis_worktree_review_json_uri:
- daxis_worktree_review_json_sha256:

## Proof Item Milestones

| Milestone | item_id                                         |
| --------- | ----------------------------------------------- |
| M0        | `daxis_architecture_docs`                       |
| M0        | `daxis_names_axon_default_browser_engine`       |
| M1        | `daxis_descriptor_endpoint`                     |
| M1        | `daxis_frontend_flow`                           |
| M2        | `daxis_read_access_plan_endpoint`               |
| M2        | `storage_cors_proxy_validation`                 |
| M4        | `production_dashboards`                         |
| M4        | `production_runbooks`                           |
| M4        | `rollout_controls`                              |
| M4        | `production_table_compatibility_dashboard`      |

## External Proof Items

Use the matching guidance for `item_id`.

Attach Daxis external-state helper output for the rollout segment before accepting any item.
Set `environment_class` to `production`; development or staging proof cannot satisfy stable default routing.
Set `release_channel` to the Daxis rollout channel that the proof supports.
The only allowed `release_channel` values are `experimental`, `integration`, `candidate`, and `stable`; stable default promotion requires `stable`.
Set `axon_release_commit_sha` and `axon_release_ref` to the exact Axon release commit and branch or tag under review.
Helper output must include the Daxis commit SHA, branch or detached-ref label, origin remote URL, and working-tree status from `git rev-parse HEAD`, `git rev-parse --abbrev-ref HEAD`, `git remote get-url origin`, and `git status --short`.
Attach the helper JSON summary generated by `bash tests/conformance/verify_daxis_external_state.sh --json`.
To write an attachment-ready artifact and print its digest, run `bash tests/conformance/verify_daxis_external_state.sh --write-json path/to/external-state.json`.
The helper JSON summary must use `schema_version` `daxis.external_state.v1`.
Attach the SHA-256 digest of that helper JSON summary in `daxis_external_state_json_sha256`.
Record only the 64-character lowercase hexadecimal digest generated from the exact helper JSON bytes, for example with `shasum -a 256 path/to/external-state.json`.
Strict local proof validation parses helper JSON and requires attachment metadata to match its schema version, Daxis commit SHA, ref, origin remote URL, worktree status, contract-test status, and architecture-scan status.
Classify the Daxis working-tree review as `clean`, `dirty_reviewed`, or `dirty_rejected`; do not accept proof from a dirty Daxis checkout without owner review that ties every modified or untracked path to the rollout segment.
Set `daxis_worktree_status` to the helper JSON `daxis_worktree_status` value: `clean` or `dirty`.
Set `daxis_worktree_review` to `clean`, `dirty_reviewed`, or `dirty_rejected`; stable default promotion accepts only `clean` or `dirty_reviewed`.
When `daxis_worktree_status` is `dirty`, attach a `daxis.dirty_worktree_review.v1` JSON artifact in `daxis_worktree_review_json_uri` and its exact SHA-256 digest in `daxis_worktree_review_json_sha256`.
Use `docs/release-gates/daxis-dirty-worktree-review-template.json` as the starting shape for the dirty review artifact.
That review JSON must use `review_state` `accepted`, must match the helper JSON Daxis commit SHA, ref, origin remote URL, worktree status, worktree review, and `daxis_worktree_status_lines`, and must list each dirty path in `reviewed_paths`.
Before stable default promotion, validate a completed proof attachment with `bash tests/conformance/verify_daxis_external_proof_attachment.sh --stable-default path/to/completed-proof-attachment.md`.
Before stable default promotion, validate the completed proof attachment set with `bash tests/conformance/verify_daxis_external_proof_attachment.sh --stable-default-dir path/to/completed-proof-attachments`.
When the proof packet contains local helper JSON artifacts, validate a completed proof attachment with `bash tests/conformance/verify_daxis_external_proof_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default path/to/completed-proof-attachment.md`.
When the proof packet contains local helper JSON artifacts, validate the completed proof attachment set with `bash tests/conformance/verify_daxis_external_proof_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default-dir path/to/completed-proof-attachments`.

### `daxis_architecture_docs`

- Attach Daxis architecture doc links or commit SHAs.
- Attach the Daxis browser read-compute terminology diff.

### `daxis_names_axon_default_browser_engine`

- Attach the Daxis product architecture reference naming Axon as the default browser read engine.
- Attach release-channel or rollout approval.

### `daxis_descriptor_endpoint`

- Attach endpoint test output for `POST /v1/query/delta/snapshot-descriptor`.
- Attach expiry, snapshot mismatch, path escape, and malformed descriptor negative test output.
- Attach request and correlation ID propagation logs.

### `daxis_frontend_flow`

- Attach Daxis frontend open/query/cancel test output.
- Attach worker command capture showing no credential profile identifiers or secrets.

### `daxis_read_access_plan_endpoint`

- Attach endpoint test output for `POST /v1/catalog/read-access-plan`.
- Attach policy-denied and policy-unknown test output.

### `storage_cors_proxy_validation`

- Attach production XML endpoint CORS validation output.
- Attach URL redaction evidence for logs and UI events.

### `production_dashboards`

- Attach dashboard URLs.

### `production_runbooks`

- Attach oncall ownership and escalation policy.

### `rollout_controls`

- Attach rollout configuration schema.
- Attach server fallback routing proof.

### `production_table_compatibility_dashboard`

- Attach compatibility dashboard URL.
- Attach blocked or fallback table-class list.

## Review State

- attached
- reviewed
- accepted
- rejected

## Review

- Daxis product owner
- Daxis platform owner
- Daxis catalog/storage owner
- Daxis web platform owner
- Daxis security owner
- Daxis SRE owner
- Axon runtime / engine owner
EOF
}

write_external_proof_handoff() {
	cat >"$repo_root/docs/integrations/daxis/daxis-external-proof-handoff.md" <<'EOF'
# Daxis External Proof Handoff

The machine-readable packet is `docs/release-gates/daxis-external-proof-packet.json`, checked by
`bash tests/conformance/verify_daxis_external_proof_packet.sh`.

Every Daxis proof attachment should use `docs/release-gates/daxis-external-proof-attachment-template.md`
and carry the metadata named in `proofAttachmentSchema`.

The Daxis verification plan includes:

- `AXON_DAXIS_PLATFORM_REPO_ROOT=/path/to/daxis-platform bash tests/conformance/verify_daxis_external_state.sh`
- `AXON_DAXIS_PLATFORM_REPO_ROOT=/path/to/daxis-platform bash tests/conformance/verify_daxis_external_state.sh --json`
- `daxis.external_state.v1`
- `git rev-parse HEAD`
- `git rev-parse --abbrev-ref HEAD`
- `git remote get-url origin`
- `git status --short`
- `cargo test -p daxis-query --test contracts`
- `rg -n "Axon browser WASM|Browser read compute|Headless query gateway" README.md CLAUDE.md docs/architecture/daxis-control-plane-architecture.md crates/daxis-query`
- `daxis_external_state_json_sha256`
- `daxis_worktree_review_json_uri`
- `daxis_worktree_review_json_sha256`
- `docs/release-gates/daxis-dirty-worktree-review-template.json`
- `proofAttachmentSchema.dirtyWorktreeReviewTemplatePath`
- `proofAttachmentSchema.allowedReleaseChannels`
- `proofAttachmentSchema.allowedDaxisWorktreeStatuses`
- `proofAttachmentSchema.allowedDaxisWorktreeReviews`
- `proofAttachmentSchema.acceptedDaxisWorktreeReviews`
- `proofAttachmentSchema.checksumFormat`
- `proofAttachmentSchema.dirtyWorktreeReviewChecksumFormat`
- `proofAttachmentSchema.requiredReviewerRoles`
- `proofAttachmentSchema.requiredEnvironmentClass`
- `proofAttachmentSchema.stableDefaultValidationCommand`
- `proofAttachmentSchema.stableDefaultDirectoryValidationCommand`
- `proofAttachmentSchema.stableDefaultArtifactValidationCommand`
- `proofAttachmentSchema.stableDefaultArtifactDirectoryValidationCommand`
- strict local proof validation parses helper JSON and requires attachment metadata to match its schema version, Daxis commit SHA, ref, origin remote URL, worktree status, contract-test status, and architecture-scan status
- `requiredReleaseEvidenceArtifactCommand`
- `bash tests/conformance/verify_daxis_release_evidence.sh --write-log path/to/release-evidence.log`
- `bash tests/conformance/verify_daxis_release_evidence.sh --list`
- `stableDefaultPromotionPacketValidationCommand`
- `requiredReleaseAttachmentSchemaFields`
- `requiredProofAttachmentSchemaFields`
- `environment_class`
- `release_channel`
- allowedReleaseChannels
- allowedDaxisWorktreeStatuses
- allowedDaxisWorktreeReviews
- acceptedDaxisWorktreeReviews
- `axon_release_commit_sha`
- `axon_release_ref`
- `rollout_segment`
- `daxis_stable_default_release_identity_verified=true`
- one Axon release commit
- one Axon release ref
- production-environment-scoped
- `64-character lowercase hexadecimal digest`
- `shasum -a 256 path/to/external-state.json`
- `bash tests/conformance/verify_daxis_external_proof_attachment.sh --stable-default path/to/completed-proof-attachment.md`
- `bash tests/conformance/verify_daxis_external_proof_attachment.sh --stable-default-dir path/to/completed-proof-attachments`
- `bash tests/conformance/verify_daxis_external_proof_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default path/to/completed-proof-attachment.md`
- `bash tests/conformance/verify_daxis_external_proof_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default-dir path/to/completed-proof-attachments`
- `bash tests/conformance/verify_daxis_stable_default_promotion_packet.sh --artifact-root path/to/artifacts --release-attachments path/to/completed-release-attachments --proof-attachments path/to/completed-proof-attachments --release-evidence-log path/to/release-evidence.log --release-evidence-sha256 <sha256> --release-evidence-exit-status 0`

External proof items:

- `daxis_architecture_docs`
- `daxis_names_axon_default_browser_engine`
- `daxis_descriptor_endpoint`
- `daxis_frontend_flow`
- `daxis_read_access_plan_endpoint`
- `storage_cors_proxy_validation`
- `production_dashboards`
- `production_runbooks`
- `rollout_controls`
- `production_table_compatibility_dashboard`

The `stableDefaultPromotionGate` requires release-process attachments for:

- `currentPromotionState`
- `blocked_external_proof_required`

- `git_sha`
- `worker_artifact_size`
- `public_gcs_live_smoke`
- `release_notes`
- `migration_notes`

It also requires `bash tests/conformance/verify_daxis_release_evidence.sh`,
accepted Daxis external proof, `requiredReleaseChannel` `stable`, and
`server_fallback` rollback evidence.
EOF
}

write_dirty_worktree_review_template() {
	cat >"$repo_root/docs/release-gates/daxis-dirty-worktree-review-template.json" <<'EOF'
{
  "schema_version": "daxis.dirty_worktree_review.v1",
  "review_state": "accepted",
  "reviewed_at": "YYYY-MM-DDTHH:MM:SSZ",
  "reviewer": "Daxis owner name",
  "reviewer_role": "Daxis platform owner",
  "rollout_segment": "stable_default_segment",
  "daxis_commit_sha": "40-character lowercase git SHA",
  "daxis_ref": "main",
  "daxis_origin_remote_url": "https://github.com/daxis-io/daxis-platform.git",
  "daxis_worktree_status": "dirty",
  "daxis_worktree_review": "dirty_reviewed",
  "daxis_worktree_status_lines": [
    " M path/to/modified-file",
    "?? path/to/untracked-file"
  ],
  "reviewed_paths": [
    "path/to/modified-file",
    "path/to/untracked-file"
  ],
  "notes": "Explain why each dirty path is accepted for this rollout segment."
}
EOF
}

write_external_state_helper() {
	cat >"$repo_root/tests/conformance/verify_daxis_external_state.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

case "${1:-}" in
  --list)
    printf '%s\n' \
      "git rev-parse HEAD" \
      "git rev-parse --abbrev-ref HEAD" \
      "git remote get-url origin" \
      "git status --short" \
      "cargo test -p daxis-query --test contracts" \
      "rg -n \"Axon browser WASM|Browser read compute|Headless query gateway\" README.md CLAUDE.md docs/architecture/daxis-control-plane-architecture.md crates/daxis-query"
    ;;
  *)
    exit 0
    ;;
esac
EOF
}

write_external_blocker_register() {
	cat >"$repo_root/docs/release-gates/browser-wasm-delta-gcs-external-blockers.md" <<'EOF'
# Browser WASM + Delta on GCS External Blockers

## Stable Default External Proof Items

The `stableDefaultPromotionGate` remains `blocked_external_proof_required` until each Daxis-owned proof item below is attached, reviewed, accepted, and tied to `server_fallback` rollback evidence:

| Milestone | Proof item                                      |
| --------- | ----------------------------------------------- |
| M0        | `daxis_architecture_docs`                       |
| M0        | `daxis_names_axon_default_browser_engine`       |
| M1        | `daxis_descriptor_endpoint`                     |
| M1        | `daxis_frontend_flow`                           |
| M2        | `daxis_read_access_plan_endpoint`               |
| M2        | `storage_cors_proxy_validation`                 |
| M4        | `production_dashboards`                         |
| M4        | `production_runbooks`                           |
| M4        | `rollout_controls`                              |
| M4        | `production_table_compatibility_dashboard`      |
EOF
}

write_proof_attachment_template
write_external_proof_handoff
write_dirty_worktree_review_template
write_external_state_helper
write_external_blocker_register

write_valid_packet() {
	python3 - "$packet" "$traceability" "$release_bundle" "$rollout_register" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
traceability_path = Path(sys.argv[2])
release_bundle_path = Path(sys.argv[3])
rollout_register_path = Path(sys.argv[4])
operational_readiness_path = release_bundle_path.parent / "daxis-operational-readiness.json"
items = [
    ("daxis_architecture_docs", "M0"),
    ("daxis_names_axon_default_browser_engine", "M0"),
    ("daxis_descriptor_endpoint", "M1"),
    ("daxis_frontend_flow", "M1"),
    ("daxis_read_access_plan_endpoint", "M2"),
    ("storage_cors_proxy_validation", "M2"),
    ("production_dashboards", "M4"),
    ("production_runbooks", "M4"),
    ("rollout_controls", "M4"),
    ("production_table_compatibility_dashboard", "M4"),
]
packet = {
    "packet": "daxis_external_proof_packet",
    "scope": "test fixture",
    "sourceDocs": [
        "docs/adr/ADR-0008-daxis-browser-read-compute-contract.md",
        "docs/release-gates/daxis-strategy-traceability.json",
        "docs/release-gates/daxis-release-bundle-manifest.json",
        "docs/release-gates/daxis-production-rollout-decisions.json",
        "docs/release-gates/daxis-operational-readiness.json",
        "docs/release-gates/browser-wasm-delta-gcs-external-blockers.md",
        "docs/integrations/daxis/daxis-external-proof-handoff.md",
        "docs/integrations/daxis/daxis-first-class-integration-strategy.md",
        "docs/release-gates/daxis-external-proof-attachment-template.md",
        "docs/release-gates/daxis-dirty-worktree-review-template.json",
    ],
    "daxisVerificationPlan": {
        "purpose": "Current-state checks Daxis owners run before attaching proof.",
        "axonHelperCommand": "bash tests/conformance/verify_daxis_external_state.sh",
        "jsonSummaryCommand": "bash tests/conformance/verify_daxis_external_state.sh --json",
        "jsonArtifactCommand": "bash tests/conformance/verify_daxis_external_state.sh --write-json path/to/external-state.json",
        "activeArchitecturePaths": [
            "README.md",
            "CLAUDE.md",
            "docs/architecture/daxis-control-plane-architecture.md",
            "crates/daxis-query/src/lib.rs",
            "crates/daxis-query/tests/contracts.rs",
        ],
        "commands": [
            "git rev-parse HEAD",
            "git rev-parse --abbrev-ref HEAD",
            "git remote get-url origin",
            "git status --short",
            "cargo test -p daxis-query --test contracts",
            "rg -n \"Axon browser WASM|Browser read compute|Headless query gateway\" README.md CLAUDE.md docs/architecture/daxis-control-plane-architecture.md crates/daxis-query",
        ],
    },
    "proofAttachmentSchema": {
        "purpose": "Minimum metadata every Daxis proof attachment carries during rollout review.",
        "templatePath": "docs/release-gates/daxis-external-proof-attachment-template.md",
        "dirtyWorktreeReviewTemplatePath": "docs/release-gates/daxis-dirty-worktree-review-template.json",
        "requiredMetadata": [
            "item_id",
            "milestone",
            "owner",
            "captured_at",
            "environment",
            "environment_class",
            "release_channel",
            "axon_release_commit_sha",
            "axon_release_ref",
            "rollout_segment",
            "artifact_uri",
            "verification_command_or_url",
            "exit_status_or_review_status",
            "rollback_evidence_uri",
            "daxis_commit_sha",
            "daxis_ref",
            "daxis_origin_remote_url",
            "daxis_worktree_status",
            "daxis_worktree_review",
            "daxis_external_state_schema_version",
            "daxis_external_state_json_uri",
            "daxis_external_state_json_sha256",
            "daxis_worktree_review_json_uri",
            "daxis_worktree_review_json_sha256",
        ],
        "requiredEnvironmentClass": "production",
        "allowedReleaseChannels": ["experimental", "integration", "candidate", "stable"],
        "allowedDaxisWorktreeStatuses": ["clean", "dirty"],
        "allowedDaxisWorktreeReviews": ["clean", "dirty_reviewed", "dirty_rejected"],
        "acceptedDaxisWorktreeReviews": ["clean", "dirty_reviewed"],
        "checksumFormat": {
            "field": "daxis_external_state_json_sha256",
            "algorithm": "sha256",
            "encoding": "lowercase_hex",
            "length": 64,
            "sourceBytes": "exact_helper_json_bytes",
        },
        "dirtyWorktreeReviewChecksumFormat": {
            "field": "daxis_worktree_review_json_sha256",
            "algorithm": "sha256",
            "encoding": "lowercase_hex",
            "length": 64,
            "sourceBytes": "exact_dirty_worktree_review_json_bytes",
        },
        "stableDefaultValidationCommand": "bash tests/conformance/verify_daxis_external_proof_attachment.sh --stable-default path/to/completed-proof-attachment.md",
        "stableDefaultDirectoryValidationCommand": "bash tests/conformance/verify_daxis_external_proof_attachment.sh --stable-default-dir path/to/completed-proof-attachments",
        "stableDefaultArtifactValidationCommand": "bash tests/conformance/verify_daxis_external_proof_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default path/to/completed-proof-attachment.md",
        "stableDefaultArtifactDirectoryValidationCommand": "bash tests/conformance/verify_daxis_external_proof_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default-dir path/to/completed-proof-attachments",
        "requiredReviewStates": ["attached", "reviewed", "accepted", "rejected"],
        "requiredReviewerRoles": [
            "Daxis product owner",
            "Daxis platform owner",
            "Daxis catalog/storage owner",
            "Daxis web platform owner",
            "Daxis security owner",
            "Daxis SRE owner",
            "Axon runtime / engine owner",
        ],
    },
    "externalItems": [
        {
            "id": item_id,
            "milestone": milestone,
            "owner": "Daxis owner",
            "requiredProofArtifacts": ["proof artifact"],
            "acceptanceChecks": ["acceptance check"],
            "rollbackEvidence": "server_fallback proof",
            "axonReferences": [
                "docs/integrations/daxis/daxis-first-class-integration-strategy.md",
                "docs/release-gates/daxis-strategy-traceability.json",
            ],
        }
        for item_id, milestone in items
    ],
    "stableDefaultPromotionGate": {
        "purpose": "Prevent stable_default promotion until release-process attachments and Daxis production proof are accepted.",
        "currentPromotionState": "blocked_external_proof_required",
        "requiredReleaseProcessAttachments": [
            "git_sha",
            "worker_artifact_size",
            "public_gcs_live_smoke",
            "release_notes",
            "migration_notes",
        ],
        "requiredExternalProofItemIds": [item_id for item_id, _milestone in items],
        "requiredReviewState": "accepted",
        "requiredReleaseEvidenceCommand": "bash tests/conformance/verify_daxis_release_evidence.sh",
        "requiredReleaseEvidenceArtifactCommand": "bash tests/conformance/verify_daxis_release_evidence.sh --write-log path/to/release-evidence.log",
        "stableDefaultPromotionPacketValidationCommand": "bash tests/conformance/verify_daxis_stable_default_promotion_packet.sh --artifact-root path/to/artifacts --release-attachments path/to/completed-release-attachments --proof-attachments path/to/completed-proof-attachments --release-evidence-log path/to/release-evidence.log --release-evidence-sha256 <sha256> --release-evidence-exit-status 0",
        "requiredReleaseChannel": "stable",
        "requiredRollbackState": "server_fallback",
        "requiredReleaseAttachmentSchemaFields": [
            "artifact_sha256",
            "release_channel",
            "rollout_segment",
            "releaseAttachmentSchema.allowedReleaseChannels",
            "releaseAttachmentSchema.checksumFormat",
            "releaseAttachmentSchema.requiredReviewerRoles",
            "releaseAttachmentSchema.stableDefaultValidationCommand",
            "releaseAttachmentSchema.stableDefaultDirectoryValidationCommand",
            "releaseAttachmentSchema.stableDefaultArtifactValidationCommand",
            "releaseAttachmentSchema.stableDefaultArtifactDirectoryValidationCommand",
        ],
        "requiredProofAttachmentSchemaFields": [
            "release_channel",
            "environment_class",
            "axon_release_commit_sha",
            "axon_release_ref",
            "daxis_worktree_status",
            "daxis_worktree_review",
            "daxis_external_state_json_sha256",
            "daxis_worktree_review_json_sha256",
            "proofAttachmentSchema.allowedReleaseChannels",
            "proofAttachmentSchema.allowedDaxisWorktreeStatuses",
            "proofAttachmentSchema.allowedDaxisWorktreeReviews",
            "proofAttachmentSchema.acceptedDaxisWorktreeReviews",
            "proofAttachmentSchema.requiredEnvironmentClass",
            "proofAttachmentSchema.checksumFormat",
            "proofAttachmentSchema.dirtyWorktreeReviewChecksumFormat",
            "proofAttachmentSchema.dirtyWorktreeReviewTemplatePath",
            "proofAttachmentSchema.requiredReviewerRoles",
            "proofAttachmentSchema.stableDefaultValidationCommand",
            "proofAttachmentSchema.stableDefaultDirectoryValidationCommand",
            "proofAttachmentSchema.stableDefaultArtifactValidationCommand",
            "proofAttachmentSchema.stableDefaultArtifactDirectoryValidationCommand",
        ],
        "blockerRegister": "docs/release-gates/browser-wasm-delta-gcs-external-blockers.md",
    },
    "handoffChecklist": [
        "Attach Axon release evidence output.",
        "Attach Daxis external-state helper output.",
        "Attach Daxis service endpoint test results.",
        "Attach Daxis rollout-control proof.",
        "Attach Daxis dashboard and oncall proof.",
        "Confirm server fallback rollback path.",
        "Confirm stableDefaultPromotionGate accepted state.",
    ],
}
path.parent.mkdir(parents=True, exist_ok=True)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)

milestones = {
    "M0": {"goal": "test M0", "deliverables": [], "exitCriteria": []},
    "M1": {"goal": "test M1", "deliverables": [], "exitCriteria": []},
    "M2": {"goal": "test M2", "deliverables": [], "exitCriteria": []},
    "M3": {"goal": "test M3", "deliverables": [], "exitCriteria": []},
    "M4": {"goal": "test M4", "deliverables": [], "exitCriteria": []},
}
for item_id, milestone in items:
    milestones[milestone]["deliverables"].append(
        {
            "id": item_id,
            "status": "external_required",
            "summary": "external proof required",
            "evidence": ["docs/integrations/daxis/daxis-first-class-integration-strategy.md"],
            "externalOwner": "Daxis owner",
            "externalProof": "Daxis proof",
        }
    )

matrix = {
    "matrix": "daxis_first_class_strategy_traceability",
    "strategy": "docs/integrations/daxis/daxis-first-class-integration-strategy.md",
    "milestones": milestones,
}
with open(traceability_path, "w", encoding="utf-8") as handle:
    json.dump(matrix, handle)

release_bundle = {
    "manifest": "daxis_release_bundle_manifest",
    "releaseAttachmentSchema": {
        "releaseProcessItemIds": [
            "git_sha",
            "worker_artifact_size",
            "public_gcs_live_smoke",
            "release_notes",
            "migration_notes",
        ],
        "requiredMetadata": ["artifact_sha256", "release_channel", "rollout_segment"],
        "allowedReleaseChannels": ["experimental", "integration", "candidate", "stable"],
        "checksumFormat": {
            "field": "artifact_sha256",
            "algorithm": "sha256",
            "encoding": "lowercase_hex",
            "length": 64,
            "sourceBytes": "exact_release_evidence_artifact_bytes",
        },
        "stableDefaultValidationCommand": "bash tests/conformance/verify_daxis_release_attachment.sh --stable-default path/to/completed-release-attachment.md",
        "stableDefaultDirectoryValidationCommand": "bash tests/conformance/verify_daxis_release_attachment.sh --stable-default-dir path/to/completed-release-attachments",
        "stableDefaultArtifactValidationCommand": "bash tests/conformance/verify_daxis_release_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default path/to/completed-release-attachment.md",
        "stableDefaultArtifactDirectoryValidationCommand": "bash tests/conformance/verify_daxis_release_attachment.sh --artifact-root path/to/artifacts --require-local-artifacts --stable-default-dir path/to/completed-release-attachments",
        "requiredReviewerRoles": ["Release owner"],
    },
    "releaseEvidenceCommands": ["bash tests/conformance/verify_daxis_release_evidence.sh"],
    "releaseEvidenceArtifactCommand": "bash tests/conformance/verify_daxis_release_evidence.sh --write-log path/to/release-evidence.log",
    "stableDefaultPromotionPacketValidationCommand": "bash tests/conformance/verify_daxis_stable_default_promotion_packet.sh --artifact-root path/to/artifacts --release-attachments path/to/completed-release-attachments --proof-attachments path/to/completed-proof-attachments --release-evidence-log path/to/release-evidence.log --release-evidence-sha256 <sha256> --release-evidence-exit-status 0",
    "bundleItems": [
        {"id": "git_sha", "status": "release_process_required"},
        {"id": "worker_artifact_size", "status": "release_process_required"},
        {"id": "public_gcs_live_smoke", "status": "release_process_required"},
        {"id": "release_notes", "status": "release_process_required"},
        {"id": "migration_notes", "status": "release_process_required"},
    ],
}
with open(release_bundle_path, "w", encoding="utf-8") as handle:
    json.dump(release_bundle, handle)

operational_readiness = {
    "readiness": "daxis_m4_operational_maturity",
    "releaseEvidenceAutomation": {
        "runner": "tests/conformance/verify_daxis_release_evidence.sh",
        "artifactCommand": "bash tests/conformance/verify_daxis_release_evidence.sh --write-log path/to/release-evidence.log",
    },
}
with open(operational_readiness_path, "w", encoding="utf-8") as handle:
    json.dump(operational_readiness, handle)

rollout_register = {
    "register": "daxis_production_rollout_decisions",
    "decisions": {
        "releaseChannels": {
            "stableDefaultGate": {
                "externalProofPacket": "docs/release-gates/daxis-external-proof-packet.json",
                "releaseBundleManifest": "docs/release-gates/daxis-release-bundle-manifest.json",
                "requiredReleaseProcessAttachments": [
                    "git_sha",
                    "worker_artifact_size",
                    "public_gcs_live_smoke",
                    "release_notes",
                    "migration_notes",
                ],
                "requiredExternalProofItemIds": [item_id for item_id, _milestone in items],
                "requiredReviewState": "accepted",
                "requiredReleaseEvidenceCommand": "bash tests/conformance/verify_daxis_release_evidence.sh",
                "requiredReleaseEvidenceArtifactCommand": "bash tests/conformance/verify_daxis_release_evidence.sh --write-log path/to/release-evidence.log",
                "requiredReleaseChannel": "stable",
                "requiredRollbackState": "server_fallback",
                "requiredReleaseAttachmentSchemaFields": [
                    "artifact_sha256",
                    "release_channel",
                    "rollout_segment",
                    "releaseAttachmentSchema.allowedReleaseChannels",
                    "releaseAttachmentSchema.checksumFormat",
                    "releaseAttachmentSchema.requiredReviewerRoles",
                    "releaseAttachmentSchema.stableDefaultValidationCommand",
                    "releaseAttachmentSchema.stableDefaultDirectoryValidationCommand",
                    "releaseAttachmentSchema.stableDefaultArtifactValidationCommand",
                    "releaseAttachmentSchema.stableDefaultArtifactDirectoryValidationCommand",
                ],
                "requiredProofAttachmentSchemaFields": [
                    "release_channel",
                    "environment_class",
                    "axon_release_commit_sha",
                    "axon_release_ref",
                    "daxis_worktree_status",
                    "daxis_worktree_review",
                    "daxis_external_state_json_sha256",
                    "daxis_worktree_review_json_sha256",
                    "proofAttachmentSchema.allowedDaxisWorktreeStatuses",
                    "proofAttachmentSchema.allowedDaxisWorktreeReviews",
                    "proofAttachmentSchema.acceptedDaxisWorktreeReviews",
                    "proofAttachmentSchema.allowedReleaseChannels",
                    "proofAttachmentSchema.requiredEnvironmentClass",
                    "proofAttachmentSchema.checksumFormat",
                    "proofAttachmentSchema.dirtyWorktreeReviewChecksumFormat",
                    "proofAttachmentSchema.dirtyWorktreeReviewTemplatePath",
                    "proofAttachmentSchema.requiredReviewerRoles",
                    "proofAttachmentSchema.stableDefaultValidationCommand",
                    "proofAttachmentSchema.stableDefaultDirectoryValidationCommand",
                    "proofAttachmentSchema.stableDefaultArtifactValidationCommand",
                    "proofAttachmentSchema.stableDefaultArtifactDirectoryValidationCommand",
                ],
                "currentPromotionState": "blocked_external_proof_required",
                "blockerRegister": "docs/release-gates/browser-wasm-delta-gcs-external-blockers.md",
            }
        }
    },
}
with open(rollout_register_path, "w", encoding="utf-8") as handle:
    json.dump(rollout_register, handle)
PY
}

verify_fixture() {
	AXON_DAXIS_EXTERNAL_PROOF_REPO_ROOT="$repo_root" \
		AXON_DAXIS_EXTERNAL_PROOF_PACKET_FILE="$packet" \
		bash tests/conformance/verify_daxis_external_proof_packet.sh >/dev/null 2>&1
}

write_valid_packet
verify_fixture

python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("dirtyWorktreeReviewTemplatePath")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected proof attachment schema missing dirty worktree review template path to be rejected" >&2
	exit 1
fi
write_valid_packet

python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["sourceDocs"].remove("docs/adr/ADR-0008-daxis-browser-read-compute-contract.md")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis architecture ADR source doc to be rejected" >&2
	exit 1
fi
write_valid_packet

python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["daxisVerificationPlan"].pop("axonHelperCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external-state helper command to be rejected" >&2
	exit 1
fi
write_valid_packet

python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["daxisVerificationPlan"].pop("jsonSummaryCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external-state JSON summary command to be rejected" >&2
	exit 1
fi
write_valid_packet

python3 - "$repo_root/tests/conformance/verify_daxis_external_state.sh" <<'PY'
import sys

path = sys.argv[1]
with open(path, "w", encoding="utf-8") as handle:
    handle.write(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "case \"${1:-}\" in\n"
        "  --list)\n"
        "    printf '%s\\n' \"cargo test -p daxis-query --test contracts\"\n"
        "    ;;\n"
        "  *) exit 0 ;;\n"
        "esac\n"
    )
PY

if verify_fixture; then
	echo "expected stale Daxis external-state helper command list to be rejected" >&2
	exit 1
fi
write_external_state_helper
write_valid_packet

python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["sourceDocs"].append("docs/integrations/daxis/daxis-first-class-integration-strategy.md")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate external proof source docs to be rejected" >&2
	exit 1
fi
write_valid_packet

write_external_proof_handoff
python3 - "$repo_root/docs/integrations/daxis/daxis-external-proof-handoff.md" <<'PY'
import sys

path = sys.argv[1]
with open(path, "w", encoding="utf-8") as handle:
    handle.write(
        "# Daxis External Proof Handoff\n\n"
        "Attach the external proof packet before rollout review.\n"
    )
PY

if verify_fixture; then
	echo "expected stale external proof handoff doc to be rejected" >&2
	exit 1
fi
write_external_proof_handoff

python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["externalItems"] = [
    item for item in packet["externalItems"] if item["id"] != "production_runbooks"
]
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing production runbooks proof item to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import copy
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["externalItems"].append(copy.deepcopy(packet["externalItems"][0]))
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate external proof items to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'PY'
import sys

path = sys.argv[1]
with open(path, "w", encoding="utf-8") as handle:
    handle.write(
        "# Daxis External Proof Attachment Template\n\n"
        "Do not attach browser-visible secrets, signed URLs, raw credentials, service-account material, private customer identifiers, or unredacted tenant data.\n\n"
        "## Proof Attachment Metadata\n\n"
        "- item_id:\n"
        "- milestone:\n"
        "- owner:\n"
        "- captured_at:\n"
        "- environment:\n"
        "- rollout_segment:\n"
        "- artifact_uri:\n"
        "- verification_command_or_url:\n"
        "- exit_status_or_review_status:\n"
        "- rollback_evidence_uri:\n\n"
        "## External Proof Items\n\n"
        "- daxis_architecture_docs\n"
        "- daxis_names_axon_default_browser_engine\n"
        "- daxis_descriptor_endpoint\n"
        "- daxis_frontend_flow\n"
        "- daxis_read_access_plan_endpoint\n"
        "- storage_cors_proxy_validation\n"
        "- production_dashboards\n"
        "- production_runbooks\n"
        "- rollout_controls\n"
        "- production_table_compatibility_dashboard\n\n"
        "## Review State\n\n"
        "- attached\n"
        "- reviewed\n"
        "- accepted\n"
        "- rejected\n"
    )
PY

if verify_fixture; then
	echo "expected proof attachment template missing per-item evidence guidance to be rejected" >&2
	exit 1
fi
write_proof_attachment_template

python3 - "$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace(
    "Attach Daxis external-state helper output for the rollout segment before accepting any item.\n",
    "",
)
path.write_text(text, encoding="utf-8")
PY

if verify_fixture; then
	echo "expected proof attachment template missing external-state helper output guidance to be rejected" >&2
	exit 1
fi
write_proof_attachment_template

python3 - "$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace(
    "Helper output must include the Daxis commit SHA, branch or detached-ref label, origin remote URL, and working-tree status from `git rev-parse HEAD`, `git rev-parse --abbrev-ref HEAD`, `git remote get-url origin`, and `git status --short`.\n",
    "",
)
path.write_text(text, encoding="utf-8")
PY

if verify_fixture; then
	echo "expected proof attachment template missing external-state git attribution guidance to be rejected" >&2
	exit 1
fi
write_proof_attachment_template

python3 - "$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("| M1        | `daxis_descriptor_endpoint`                     |\n", "|           | `daxis_descriptor_endpoint`                     |\n")
path.write_text(text, encoding="utf-8")
PY

if verify_fixture; then
	echo "expected proof attachment template missing external proof milestone to be rejected" >&2
	exit 1
fi
write_proof_attachment_template

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["externalItems"][0].pop("rollbackEvidence")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing rollback evidence to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["externalItems"][0].pop("axonReferences")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Axon references to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["handoffChecklist"].remove("Attach Daxis rollout-control proof.")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing handoff checklist item to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["handoffChecklist"].remove("Attach Daxis external-state helper output.")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external-state handoff checklist item to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["handoffChecklist"].remove("Confirm stableDefaultPromotionGate accepted state.")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing stableDefaultPromotionGate handoff checklist item to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet.pop("daxisVerificationPlan")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis verification plan to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["daxisVerificationPlan"]["commands"] = [
    command
    for command in packet["daxisVerificationPlan"]["commands"]
    if command != "cargo test -p daxis-query --test contracts"
]
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis query contract verification command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["daxisVerificationPlan"]["activeArchitecturePaths"].append("README.md")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate Daxis active architecture paths to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["daxisVerificationPlan"]["commands"].append("cargo test -p daxis-query --test contracts")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate Daxis verification commands to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["daxisVerificationPlan"]["commands"].append(
    "cargo test -p daxis-query --test stale-contract"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected unsupported Daxis verification command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet.pop("proofAttachmentSchema")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing proof attachment schema to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet.pop("stableDefaultPromotionGate")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing stable default promotion gate to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"].pop("currentPromotionState")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing current promotion state to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"].pop("requiredReleaseChannel")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing stable release channel to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"].pop("stableDefaultPromotionPacketValidationCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing promotion packet validation command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"].pop("requiredReleaseEvidenceArtifactCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing release evidence artifact command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$repo_root/docs/release-gates/daxis-operational-readiness.json" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    readiness = json.load(handle)
readiness["releaseEvidenceAutomation"]["artifactCommand"] = (
    "bash tests/conformance/verify_daxis_release_evidence.sh --write-log path/to/stale-release-evidence.log"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(readiness, handle)
PY

if verify_fixture; then
	echo "expected operational readiness release evidence artifact command drift to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredReviewState"] = "reviewed"
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate without accepted review state to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredProofAttachmentSchemaFields"].remove(
    "proofAttachmentSchema.requiredReviewerRoles"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing proof reviewer-role schema field to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredProofAttachmentSchemaFields"].remove(
    "proofAttachmentSchema.dirtyWorktreeReviewTemplatePath"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing dirty worktree review template schema field to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredProofAttachmentSchemaFields"].remove(
    "axon_release_commit_sha"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing Axon release commit schema field to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredProofAttachmentSchemaFields"].remove(
    "axon_release_ref"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing Axon release ref schema field to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredReleaseAttachmentSchemaFields"].remove(
    "release_channel"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing release-channel schema field to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredReleaseAttachmentSchemaFields"].remove(
    "rollout_segment"
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing rollout-segment schema field to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredReleaseProcessAttachments"].remove("public_gcs_live_smoke")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing public GCS release attachment to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredExternalProofItemIds"].remove("rollout_controls")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing rollout-controls proof to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$release_bundle" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    manifest = json.load(handle)
manifest["releaseAttachmentSchema"]["releaseProcessItemIds"].append("release_decision_record")
manifest["bundleItems"].append({"id": "release_decision_record", "status": "release_process_required"})
with open(path, "w", encoding="utf-8") as handle:
    json.dump(manifest, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate missing release bundle process item to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["stableDefaultPromotionGate"]["requiredReleaseProcessAttachments"].append("stale_release_attachment")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate stale release attachment to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$rollout_register" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    register = json.load(handle)
gate = register["decisions"]["releaseChannels"]["stableDefaultGate"]
gate["blockerRegister"] = "docs/release-gates/stale-external-blockers.md"
with open(path, "w", encoding="utf-8") as handle:
    json.dump(register, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate blocker-register drift from rollout register to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$repo_root/docs/release-gates/browser-wasm-delta-gcs-external-blockers.md" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("| M1        | `daxis_descriptor_endpoint`                     |\n", "")
path.write_text(text, encoding="utf-8")
PY

if verify_fixture; then
	echo "expected external blocker register missing stable-default proof item to be rejected" >&2
	exit 1
fi
write_external_blocker_register

write_valid_packet
python3 - "$repo_root/docs/release-gates/browser-wasm-delta-gcs-external-blockers.md" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("| M1        | `daxis_descriptor_endpoint`                     |\n", "|           | `daxis_descriptor_endpoint`                     |\n")
path.write_text(text, encoding="utf-8")
PY

if verify_fixture; then
	echo "expected external blocker register missing stable-default proof milestone to be rejected" >&2
	exit 1
fi
write_external_blocker_register

write_valid_packet
python3 - "$rollout_register" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    register = json.load(handle)
gate = register["decisions"]["releaseChannels"]["stableDefaultGate"]
gate["requiredReleaseProcessAttachments"].remove("public_gcs_live_smoke")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(register, handle)
PY

if verify_fixture; then
	echo "expected stable default promotion gate release-attachment drift from rollout register to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["externalItems"][0]["owner"] = "Different Daxis owner"
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected external proof owner drift from traceability matrix to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("templatePath")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing proof attachment template path to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'PY'
import sys

path = sys.argv[1]
with open(path, "w", encoding="utf-8") as handle:
    handle.write(
        "# Daxis External Proof Attachment Template\n\n"
        "Do not attach browser-visible secrets, signed URLs, raw credentials, service-account material, private customer identifiers, or unredacted tenant data.\n\n"
        "## Proof Attachment Metadata\n\n"
        "- item_id:\n"
        "- milestone:\n"
        "- owner:\n"
        "- captured_at:\n"
        "- environment:\n"
        "- rollout_segment:\n"
        "- artifact_uri:\n"
        "- verification_command_or_url:\n"
        "- exit_status_or_review_status:\n"
        "- rollback_evidence_uri:\n"
        "- daxis_commit_sha:\n"
        "- daxis_ref:\n"
        "- daxis_origin_remote_url:\n"
        "- daxis_worktree_status:\n"
        "- daxis_worktree_review:\n"
    )
PY

if verify_fixture; then
	echo "expected proof attachment template missing evidence guidance to be rejected" >&2
	exit 1
fi
write_proof_attachment_template

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("rollback_evidence_uri")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing rollback evidence attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].append("item_id")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate proof attachment metadata fields to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("daxis_worktree_review")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis working-tree review attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("daxis_external_state_schema_version")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external-state schema-version attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("daxis_external_state_json_sha256")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external-state JSON checksum attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("release_channel")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis proof release-channel attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("axon_release_commit_sha")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Axon release commit attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("axon_release_ref")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Axon release ref attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredMetadata"].remove("environment_class")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis proof environment-class attachment metadata to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("requiredEnvironmentClass")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis proof production environment-class requirement to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("allowedReleaseChannels")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected proof attachment schema missing allowed release channels to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("acceptedDaxisWorktreeReviews")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected proof attachment schema missing accepted Daxis worktree reviews to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredEnvironmentClass"] = "staging"
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected non-production Daxis proof environment class to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$repo_root/docs/release-gates/daxis-external-proof-attachment-template.md" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace("Record only the 64-character lowercase hexadecimal digest generated from the exact helper JSON bytes, for example with `shasum -a 256 path/to/external-state.json`.\n", "")
path.write_text(text, encoding="utf-8")
PY

if verify_fixture; then
	echo "expected missing Daxis external-state JSON checksum format guidance to be rejected" >&2
	exit 1
fi

write_proof_attachment_template
write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("checksumFormat")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external-state checksumFormat schema to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("stableDefaultValidationCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external proof stable-default validation command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("stableDefaultDirectoryValidationCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external proof stable-default directory validation command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("stableDefaultArtifactValidationCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external proof stable-default artifact validation command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("stableDefaultArtifactDirectoryValidationCommand")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external proof stable-default artifact directory validation command to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"].pop("requiredReviewerRoles")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected missing Daxis external proof requiredReviewerRoles schema to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["proofAttachmentSchema"]["requiredReviewStates"].append("accepted")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate proof attachment review states to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$packet" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    packet = json.load(handle)
packet["handoffChecklist"].append("Confirm stableDefaultPromotionGate accepted state.")
with open(path, "w", encoding="utf-8") as handle:
    json.dump(packet, handle)
PY

if verify_fixture; then
	echo "expected duplicate external proof handoff checklist items to be rejected" >&2
	exit 1
fi

write_valid_packet
python3 - "$traceability" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as handle:
    matrix = json.load(handle)
matrix["milestones"]["M0"]["exitCriteria"].append(
    {
        "id": "daxis_architecture_default_named",
        "status": "external_required",
        "summary": "Daxis architecture names Axon as the default browser engine.",
        "evidence": ["docs/integrations/daxis/daxis-first-class-integration-strategy.md"],
        "externalOwner": "Daxis owner",
        "externalProof": "Daxis proof",
    }
)
with open(path, "w", encoding="utf-8") as handle:
    json.dump(matrix, handle)
PY

if verify_fixture; then
	echo "expected traceability external proof drift to be rejected" >&2
	exit 1
fi

echo "Daxis external proof packet verifier regression coverage passed"
