#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
verifier="$script_dir/verify_upstream_wasm_fork_stack.sh"

if [[ ! -x "$verifier" ]]; then
  echo "stack verifier regression setup failed: missing executable $verifier" >&2
  exit 1
fi

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

seed="$tmpdir/seed"
mkdir -p "$seed"
git -C "$seed" init -q
git -C "$seed" config user.name "Axon stack verifier test"
git -C "$seed" config user.email "stack-verifier@example.invalid"
printf '%s\n' "reachable revision" >"$seed/README.md"
git -C "$seed" add README.md
git -C "$seed" commit -q -m "test: seed reachable revision"
reachable_rev="$(git -C "$seed" rev-parse HEAD)"

for repository in arrow object_store datafusion delta_kernel delta_rs; do
  bare="$tmpdir/$repository.git"
  git clone -q --bare "$seed" "$bare"
done

fork_arrow="file://$tmpdir/arrow.git"
fork_object_store="file://$tmpdir/object_store.git"
fork_datafusion="file://$tmpdir/datafusion.git"
fork_delta_kernel="file://$tmpdir/delta_kernel.git"
fork_delta_rs="file://$tmpdir/delta_rs.git"

write_fixture() {
  local fixture="$1"
  local poc="$fixture/poc/upstream-wasm-fork-stack"
  mkdir -p "$poc/member"

  cat >"$poc/stack.lock.toml" <<EOF_LOCK
schema = 1
target = "wasm32-unknown-unknown"
axon_base_rev = "62d4c465e10dc329221023eaaf2c67c542c408ce"

[repositories.arrow_rs]
canonical = "https://github.com/apache/arrow-rs"
fork = "$fork_arrow"
base_rev = "$reachable_rev"
candidate_rev = "$reachable_rev"
stack_rev = "$reachable_rev"

[repositories.object_store]
canonical = "https://github.com/apache/arrow-rs-object-store"
fork = "$fork_object_store"
base_rev = "$reachable_rev"
candidate_rev = "$reachable_rev"
stack_rev = "$reachable_rev"

[repositories.datafusion]
canonical = "https://github.com/apache/datafusion"
fork = "$fork_datafusion"
base_rev = "$reachable_rev"
candidate_rev = "$reachable_rev"
stack_rev = "$reachable_rev"

[repositories.delta_kernel]
canonical = "https://github.com/delta-io/delta-kernel-rs"
compatibility_source = "https://github.com/buoyant-data/delta-kernel-rs"
fork = "$fork_delta_kernel"
base_rev = "$reachable_rev"
candidate_rev = "$reachable_rev"
stack_rev = "$reachable_rev"

[repositories.delta_rs]
canonical = "https://github.com/delta-io/delta-rs"
fork = "$fork_delta_rs"
base_rev = "$reachable_rev"
candidate_rev = "$reachable_rev"
stack_rev = "$reachable_rev"
EOF_LOCK

  cat >"$poc/Cargo.toml" <<'EOF_MANIFEST'
[workspace]
members = ["member"]
resolver = "2"
EOF_MANIFEST

  cat >"$poc/member/Cargo.toml" <<'EOF_MEMBER'
[package]
name = "stack-verifier-fixture"
version = "0.1.0"
edition = "2021"
EOF_MEMBER

  mkdir -p "$poc/member/src"
  printf '%s\n' "pub fn fixture() {}" >"$poc/member/src/lib.rs"

  cat >"$poc/Cargo.lock" <<EOF_CARGO_LOCK
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "arrow-schema"
version = "58.3.0"
source = "git+$fork_arrow?rev=$reachable_rev#$reachable_rev"

[[package]]
name = "object_store"
version = "0.13.2"
source = "git+$fork_object_store?rev=$reachable_rev#$reachable_rev"

[[package]]
name = "datafusion"
version = "53.1.0"
source = "git+$fork_datafusion?rev=$reachable_rev#$reachable_rev"

[[package]]
name = "buoyant_kernel"
version = "0.22.2"
source = "git+$fork_delta_kernel?rev=$reachable_rev#$reachable_rev"

[[package]]
name = "deltalake-browser"
version = "0.1.0"
source = "git+$fork_delta_rs?rev=$reachable_rev#$reachable_rev"
EOF_CARGO_LOCK

  python3 - "$poc/metadata.json" "$reachable_rev" \
    "$fork_arrow" \
    "$fork_object_store" \
    "$fork_datafusion" \
    "$fork_delta_kernel" \
    "$fork_delta_rs" <<'PY'
import json
import sys

output, rev, arrow, object_store, datafusion, delta_kernel, delta_rs = sys.argv[1:]
root_id = "path+file:///stack-verifier-fixture#stack-verifier-fixture@0.1.0"
specs = [
    ("arrow-schema", "58.3.0", arrow),
    ("object_store", "0.13.2", object_store),
    ("datafusion", "53.1.0", datafusion),
    ("buoyant_kernel", "0.22.2", delta_kernel),
    ("deltalake-browser", "0.1.0", delta_rs),
]
packages = [
    {
        "id": root_id,
        "name": "stack-verifier-fixture",
        "version": "0.1.0",
        "source": None,
    }
]
deps = []
nodes = []
for name, version, url in specs:
    source = f"git+{url}?rev={rev}#{rev}"
    package_id = f"{source}#{name}@{version}"
    packages.append(
        {
            "id": package_id,
            "name": name,
            "version": version,
            "source": source,
        }
    )
    deps.append(
        {
            "name": name.replace("-", "_"),
            "pkg": package_id,
            "dep_kinds": [{"kind": None, "target": None}],
        }
    )
    nodes.append({"id": package_id, "deps": []})

nodes.append({"id": root_id, "deps": deps})
with open(output, "w", encoding="utf-8") as handle:
    json.dump(
        {
            "packages": packages,
            "workspace_members": [root_id],
            "resolve": {"nodes": nodes},
        },
        handle,
    )
PY
}

run_final() {
  local fixture="$1"
  bash "$verifier" \
    --repo-root "$fixture" \
    --metadata-file "$fixture/poc/upstream-wasm-fork-stack/metadata.json"
}

run_bootstrap() {
  local fixture="$1"
  bash "$verifier" \
    --bootstrap \
    --repo-root "$fixture" \
    --metadata-file "$fixture/poc/upstream-wasm-fork-stack/metadata.json"
}

expect_failure() {
  local name="$1"
  local expected="$2"
  local fixture="$3"
  local output="$tmpdir/$name.output"
  if run_final "$fixture" >"$output" 2>&1; then
    echo "expected $name to fail" >&2
    exit 1
  fi
  if ! rg -F "$expected" "$output" >/dev/null; then
    echo "$name failed without expected diagnostic: $expected" >&2
    cat "$output" >&2
    exit 1
  fi
}

base="$tmpdir/base"
write_fixture "$base"
run_final "$base" >/dev/null

missing_repository="$tmpdir/missing-repository"
cp -R "$base" "$missing_repository"
python3 - "$missing_repository/poc/upstream-wasm-fork-stack/stack.lock.toml" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text()
text = text[: text.index("\n[repositories.delta_rs]")]
path.write_text(text + "\n")
PY
expect_failure \
  "missing-repository" \
  "missing repository entry: delta_rs" \
  "$missing_repository"

invalid_revision="$tmpdir/invalid-revision"
cp -R "$base" "$invalid_revision"
python3 - "$invalid_revision/poc/upstream-wasm-fork-stack/stack.lock.toml" "$reachable_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
rev = sys.argv[2]
path.write_text(path.read_text().replace(f'base_rev = "{rev}"', 'base_rev = "abc"', 1))
PY
expect_failure \
  "invalid-revision" \
  "arrow_rs.base_rev must be a 40-character lowercase hexadecimal revision" \
  "$invalid_revision"

unset_revision="$tmpdir/unset-revision"
cp -R "$base" "$unset_revision"
python3 - "$unset_revision/poc/upstream-wasm-fork-stack/stack.lock.toml" "$reachable_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
rev = sys.argv[2]
text = path.read_text()
text = text.replace(f'candidate_rev = "{rev}"', 'candidate_rev = "UNSET"')
text = text.replace(f'stack_rev = "{rev}"', 'stack_rev = "UNSET"')
path.write_text(text)
PY
expect_failure \
  "unset-revision" \
  "arrow_rs.candidate_rev is UNSET in final mode" \
  "$unset_revision"
rm "$unset_revision/poc/upstream-wasm-fork-stack/Cargo.lock"
run_bootstrap "$unset_revision" >/dev/null

missing_browser_lock="$tmpdir/missing-browser-lock"
cp -R "$base" "$missing_browser_lock"
rm "$missing_browser_lock/poc/upstream-wasm-fork-stack/Cargo.lock"
expect_failure \
  "missing-browser-lock" \
  "missing browser Cargo lock" \
  "$missing_browser_lock"
run_bootstrap "$missing_browser_lock" >/dev/null

unreachable_revision="$tmpdir/unreachable-revision"
cp -R "$base" "$unreachable_revision"
python3 - "$unreachable_revision/poc/upstream-wasm-fork-stack/stack.lock.toml" "$reachable_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
rev = sys.argv[2]
path.write_text(
    path.read_text().replace(
        f'candidate_rev = "{rev}"',
        'candidate_rev = "0000000000000000000000000000000000000000"',
        1,
    )
)
PY
expect_failure \
  "unreachable-revision" \
  "arrow_rs.candidate_rev is not reachable from its fork" \
  "$unreachable_revision"

mutable_branch="$tmpdir/mutable-branch"
cp -R "$base" "$mutable_branch"
cat >>"$mutable_branch/poc/upstream-wasm-fork-stack/Cargo.toml" <<'EOF_BRANCH'

[workspace.dependencies]
mutable = { git = "https://example.invalid/repository", branch = "main" }
EOF_BRANCH
expect_failure \
  "mutable-branch" \
  "mutable branch dependency" \
  "$mutable_branch"

mismatched_lock="$tmpdir/mismatched-lock"
cp -R "$base" "$mismatched_lock"
python3 - "$mismatched_lock/poc/upstream-wasm-fork-stack/Cargo.lock" "$fork_arrow" "$reachable_rev" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
url = sys.argv[2]
rev = sys.argv[3]
path.write_text(
    path.read_text().replace(
        f"git+{url}?rev={rev}#{rev}",
        f"git+{url}?rev={rev}#0000000000000000000000000000000000000000",
        1,
    )
)
PY
expect_failure \
  "mismatched-lock" \
  "Cargo.lock source mismatch for arrow_rs" \
  "$mismatched_lock"

duplicate_arrow="$tmpdir/duplicate-arrow"
cp -R "$base" "$duplicate_arrow"
python3 - "$duplicate_arrow/poc/upstream-wasm-fork-stack/metadata.json" <<'PY'
import json
from pathlib import Path
import sys

path = Path(sys.argv[1])
metadata = json.loads(path.read_text())
root = metadata["workspace_members"][0]
duplicate = {
    "id": "registry+https://github.com/rust-lang/crates.io-index#arrow-schema@59.1.0",
    "name": "arrow-schema",
    "version": "59.1.0",
    "source": "registry+https://github.com/rust-lang/crates.io-index",
}
metadata["packages"].append(duplicate)
metadata["resolve"]["nodes"].append({"id": duplicate["id"], "deps": []})
root_node = next(node for node in metadata["resolve"]["nodes"] if node["id"] == root)
root_node["deps"].append(
    {
        "name": "arrow_schema_duplicate",
        "pkg": duplicate["id"],
        "dep_kinds": [{"kind": None, "target": None}],
    }
)
path.write_text(json.dumps(metadata))
PY
expect_failure \
  "duplicate-arrow" \
  "duplicate browser package source for arrow-schema" \
  "$duplicate_arrow"

duplicate_datafusion="$tmpdir/duplicate-datafusion"
cp -R "$base" "$duplicate_datafusion"
python3 - "$duplicate_datafusion/poc/upstream-wasm-fork-stack/metadata.json" <<'PY'
import json
from pathlib import Path
import sys

path = Path(sys.argv[1])
metadata = json.loads(path.read_text())
root = metadata["workspace_members"][0]
duplicate = {
    "id": "registry+https://github.com/rust-lang/crates.io-index#datafusion@54.1.0",
    "name": "datafusion",
    "version": "54.1.0",
    "source": "registry+https://github.com/rust-lang/crates.io-index",
}
metadata["packages"].append(duplicate)
metadata["resolve"]["nodes"].append({"id": duplicate["id"], "deps": []})
root_node = next(node for node in metadata["resolve"]["nodes"] if node["id"] == root)
root_node["deps"].append(
    {
        "name": "datafusion_duplicate",
        "pkg": duplicate["id"],
        "dep_kinds": [{"kind": None, "target": None}],
    }
)
path.write_text(json.dumps(metadata))
PY
expect_failure \
  "duplicate-datafusion" \
  "duplicate browser package source for datafusion" \
  "$duplicate_datafusion"

echo "upstream WASM fork stack verifier regression coverage passed"
