schema = 1
target = "wasm32-unknown-unknown"
axon_base_rev = "62d4c465e10dc329221023eaaf2c67c542c408ce"

[repositories.arrow_rs]
canonical = "https://github.com/apache/arrow-rs"
fork = "https://github.com/daxis-io/arrow-rs"
base_rev = "913bab26ba9bed8fc2bc1acda300cc52345b0da1"
candidate_rev = "f24c67c536e98f85f2ed8a289a6eb1d55916ffb9"
stack_rev = "52c8fb2e9c28b9d89d08c313e1bc938a35c29c99"

[repositories.object_store]
canonical = "https://github.com/apache/arrow-rs-object-store"
fork = "https://github.com/daxis-io/arrow-rs-object-store"
base_rev = "7a65b75b0d26fd8a282999462cb7030fb85fdcc3"
candidate_rev = "502ec006d58e11f0921a173210d54a4485d1f5a3"
stack_rev = "ab9fda65805487edf5487e63082cab8111f0a178"

[repositories.datafusion]
canonical = "https://github.com/apache/datafusion"
fork = "https://github.com/daxis-io/datafusion"
base_rev = "eae7bf4fa1c037c0a065d1f36d0669f5bb97a9cf"
candidate_rev = "693aa0b5d2a3c925db963776a472d6144352116e"
stack_rev = "54a376b161a059d08c806d3e959b87802a85ec4f"

[repositories.delta_kernel]
canonical = "https://github.com/delta-io/delta-kernel-rs"
compatibility_source = "https://github.com/buoyant-data/delta-kernel-rs"
fork = "https://github.com/daxis-io/delta-kernel-rs"
base_rev = "f4602a43fe886f45cc3523360bc2488b8f3a2e58"
candidate_rev = "c9a475f3394adc5296c4f16587c1f69c6e87213e"
stack_rev = "056f7223af0c5c6d6e56502615c3943cfb94132a"

[repositories.delta_rs]
canonical = "https://github.com/delta-io/delta-rs"
fork = "https://github.com/daxis-io/delta-rs"
base_rev = "df72cc6d3fba014a77243ce80514a6122b46a89b"
candidate_rev = "af7764c098bf0edf92e16de3f865b84b706780f6"
stack_rev = "8e5e163f67b9c85e5a71e2671e35e8991a09e4bc"
