[package]
name = "axon-upstream-wasm-browser-harness"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arrow-array = { git = "https://github.com/daxis-io/arrow-rs", rev = "52c8fb2e9c28b9d89d08c313e1bc938a35c29c99" }
arrow-ipc = { git = "https://github.com/daxis-io/arrow-rs", rev = "52c8fb2e9c28b9d89d08c313e1bc938a35c29c99" }
browser-sdk = { path = "../../../crates/browser-sdk" }
deltalake-browser = { git = "https://github.com/daxis-io/delta-rs", rev = "8e5e163f67b9c85e5a71e2671e35e8991a09e4bc" }
js-sys = "=0.3.91"
query-contract = { path = "../../../crates/query-contract" }
url = "2"
wasm-bindgen = "=0.2.114"
wasm-bindgen-futures = "=0.4.64"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
object_store = { git = "https://github.com/daxis-io/arrow-rs-object-store", rev = "ab9fda65805487edf5487e63082cab8111f0a178", default-features = false, features = ["http-base", "reqwest", "web"] }

[dev-dependencies]
bytes = "=1.11.1"
